// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
      ElAvatar: typeof import('element-plus/es')['ElAvatar']
      ElButton: typeof import('element-plus/es')['ElButton']
      ElIcon: typeof import('element-plus/es')['ElIcon']
      ElTooltip: typeof import('element-plus/es')['ElTooltip']
      ElUpload: typeof import('element-plus/es')['ElUpload']
      RouterLink: typeof import('vue-router')['RouterLink']
      RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
